MvcWebUI/Controllers/CategoryController.cs
using Business.Abstract;
using Core.Utilities.Results.Abstract;
using Core.Utilities.Results.Concrete;
using Entities.DTOs;
using Entities.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;

namespace MvcWebUI.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IActionResult Index()
        {
            var result = _categoryService.GetAllCategories();
            return View(new AllCategoryDto
            {
                ListCategories = result.Data

            });
        }

        public IActionResult GetAllCategories()
        {
            var result = _categoryService.GetAllCategories();
            return PartialView(new AllCategoryDto
            {
                ListCategories = result.Data

            });
        }

        [HttpPost]
        public IActionResult GetById(int id)
        {
            var result = _categoryService.GetCategoryById(id);
            if (result != null)
            {
                return Json(new AllCategoryDto
                {
                    Category = result.Data
                });
            }
            TempData["Error"] = result.Message;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var getData = _categoryService.GetCategoryById(id);
            if (getData.Success)
            {
                _categoryService.DeleteCategory(getData.Data);
                return RedirectToAction("Index");
            }
            TempData["Error"] = getData.Message;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Add(AllCategoryDto model)
        {
            if (ModelState.IsValid)
            {
                var entity = new Category
                {
                    Name = model.Category.Name
                };

                var result = _categoryService.AddCategory(entity);
                if (result.Success)
                {
                    return RedirectToAction("Index");
                }
                TempData["Error"] = result.Message;
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit(AllCategoryDto model)
        {
            if (ModelState.IsValid)
            {
                var control = _categoryService.GetCategoryById(model.Category.Id);
                if (control.Success)
                {
                    var entity = new Category
                    {
                        Id = model.Category.Id,
                        Name = model.Category.Name
                    };

                    var updateMethod = _categoryService.UpdateCategory(entity);
                    if (updateMethod.Success)
                    {
                        return RedirectToAction("Index");
                    }
                    TempData["Error"] = control.Message;
                    return RedirectToAction("Index");
                }

                TempData["Error"] = control.Message;
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

MvcWebUI/Controllers/ProductController.cs
using Business.Abstract;
using Entities.DTOs;
using Entities.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;

        private readonly ICategoryService _categoryService;
        public ProductController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }

        public IActionResult Index()
        {
            var result = _productService.GetAllProducts();

            var getCategoryList = _categoryService.GetAllCategories();
            List<SelectListItem> getDropdownList = (from a in getCategoryList.Data
                                                    select new SelectListItem
                                                    {
                                                        Text = a.Name,
                                                        Value = a.Id.ToString()
                                                    }
                                                 ).ToList();
            ViewBag.Categories = getDropdownList;

            return View(new AllProductDto
            {
                ListProducts = result.Data

            });
        }


        [HttpPost]
        public IActionResult GetById(int id)
        {
            var result = _productService.GetProductById(id);
            if (result != null)
            {
                return Json(new AllProductDto
                {
                    Product = result.Data
                });
            }
            TempData["Error"] = result.Message;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var getData = _productService.GetProductById(id);
            if (getData.Success)
            {
                _productService.DeleteProduct(id);
                return RedirectToAction("Index");
            }
            TempData["Error"] = getData.Message;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Add(AllProductDto model)
        {
            var uniqueFileName = "";
            if (model.CreateProduct.ImageFile != null && model.CreateProduct.ImageFile.Length > 0)
            {
                var uploadFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images");
                uniqueFileName = string.Concat(Guid.NewGuid().ToString(), "_", model.CreateProduct.ImageFile.FileName);
                var filePath = Path.Combine(uploadFolder, uniqueFileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    model.CreateProduct.ImageFile.CopyTo(stream);
                }
            }

            var entity = new CreateProductDto
            {
                Name = model.CreateProduct.Name,
                CategoryId = model.CreateProduct.CategoryId,
                ImageSrc = uniqueFileName,
                Salesprice = model.CreateProduct.Salesprice,
            };

            var result = await _productService.AddProduct(entity);
            if (result.Success)
            {
                return RedirectToAction("Index");
            }
            TempData["Error"] = result.Message;
            return RedirectToAction("Index");

        }

        [HttpPost]
        public async Task<IActionResult> Edit(AllProductDto model)
        {
            var control = _productService.GetProductById(model.UpdateProduct.Id);
            if (control.Success)
            {
                var uniqueFileName = "";
                if (model.UpdateProduct.ImageFile != null && model.UpdateProduct.ImageFile.Length > 0)
                {
                    var uploadFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images");
                    uniqueFileName = string.Concat(Guid.NewGuid().ToString(), "_", model.UpdateProduct.ImageFile.FileName);
                    var filePath = Path.Combine(uploadFolder, uniqueFileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        model.UpdateProduct.ImageFile.CopyTo(stream);
                    }
                }

                var entity = new UpdateProductDto
                {
                    Id = model.UpdateProduct.Id,
                    Name = model.UpdateProduct.Name,
                    CategoryId = model.UpdateProduct.CategoryId,
                    ImageSrc = uniqueFileName == "" ? control.Data.ImageSrc : uniqueFileName,
                    Salesprice = model.UpdateProduct.Salesprice,
                };

                var updateMethod = await _productService.UpdateProduct(entity);
                if (updateMethod.Success)
                {
                    return RedirectToAction("Index");
                }
                TempData["Error"] = control.Message;
                return RedirectToAction("Index");
            }

            TempData["Error"] = control.Message;
            return RedirectToAction("Index");

        }
    }
}

MvcWebUI/Controllers/ReportController.cs
using Business.Abstract;
using Core.Utilities.Results.Concrete;
using Entities.DTOs;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace MvcWebUI.Controllers
{
    public class ReportController : Controller
    {
        private readonly IReportService _reportService;

        public ReportController(IReportService reportService)
        {
            _reportService = reportService;
        }

        public async Task<IActionResult> Index()
        {
            var getAllStockDetailsAsync = await _reportService.GetAllStockDetailsAsync();
            ViewBag.GetAllStockDetailsAsync = getAllStockDetailsAsync.Data;

            var getAllSaleDetailsAsync = await _reportService.GetAllSalesDetailsAsync();
            ViewBag.GetAllSaleDetailsAsync = getAllSaleDetailsAsync.Data;

            return View();
        }


    }
}

MvcWebUI/Controllers/SaleController.cs
using Business.Abstract;
using Entities.DTOs;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Threading.Tasks;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using Core.Utilities.Results.Concrete;

namespace MvcWebUI.Controllers
{
    public class SaleController : Controller
    {
        private readonly ISaleService _saleService;

        private readonly ICustomerService _customerService;

        private readonly IProductService _productService;

        private readonly IStockService _stockService;

        public SaleController(ISaleService saleService, ICustomerService customerService, IProductService productService, IStockService stockService)
        {
            _saleService = saleService;
            _customerService = customerService;
            _productService = productService;
            _stockService = stockService;
        }

        public async Task<IActionResult> Index()
        {
            var getCustomerList = _customerService.GetAllCustomers();
            List<SelectListItem> getDropdownCustomerList = (from a in getCustomerList.Data
                                                            select new SelectListItem
                                                            {
                                                                Text = string.Concat(a.Customertitle, " ", a.Customernumber),
                                                                Value = a.Id.ToString()
                                                            }
                                                 ).ToList();
            //getDropdownCustomerList.Add(new SelectListItem { Text = "Müşteri seçiniz", Value = "", Selected = true ,Disabled=true});
            ViewBag.Customers = getDropdownCustomerList;


            var getProductList = _productService.GetAllProducts();
            List<SelectListItem> getDropdownProductList = (from a in getProductList.Data
                                                           select new SelectListItem
                                                           {
                                                               Text = string.Concat(a.Name, " ", a.Salesprice, " ", "TL"),
                                                               Value = a.Id.ToString()
                                                           }
                                                 ).ToList();
            //getDropdownProductList.Add(new SelectListItem { Text = "Ürün seçiniz", Value = "", Selected = true, Disabled = true });
            ViewBag.Products = getDropdownProductList;

            var result = await _saleService.GetAllSalesAsync();

            return View(new AllSaleDto
            {
                ListSales = result.Data

            });

        }

        [HttpPost]
        public async Task<IActionResult> GetById(int id)
        {
            var result = await _saleService.GetSalesByIdAsync(id);
            if (result != null)
            {
                return Json(new AllSaleDto
                {
                    Sale = result.Data
                });
            }
            TempData["Error"] = result.Message;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var getData = _saleService.GetSalesByIdAsync(id).Result;
            if (getData.Success)
            {
                var deleteResult = _saleService.DeleteSale(id);
                if (deleteResult.Success)
                {
                    return RedirectToAction("Index");

                }
                TempData["Error"] = deleteResult.Message;
                return RedirectToAction("Index");
            }
            TempData["Error"] = getData.Message;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Add(AllSaleDto model)
        {

            var entity = new CreateSaleDto
            {
                ProductId = model.CreateSale.ProductId,
                Quantity = model.CreateSale.Quantity,
                Salesprice = model.CreateSale.Salesprice,
                CustomerId = model.CreateSale.CustomerId,
            };

            var result = _saleService.AddSale(entity);
            if (result.Success)
            {
                return RedirectToAction("Index");
            }
            TempData["Error"] = result.Message;
            return RedirectToAction("Index");

        }

        [HttpPost]
        public IActionResult Edit(AllSaleDto model)
        {
            var control = _saleService.GetSalesByIdAsync(model.UpdateSale.Id).Result;
            if (control.Success)
            {
                var entity = new UpdateSaleDto
                {
                    Id = model.UpdateSale.Id,
                    ProductId = model.UpdateSale.ProductId,
                    Quantity = model.UpdateSale.Quantity,
                    Salesprice = model.UpdateSale.Salesprice,
                    CustomerId = model.UpdateSale.CustomerId,
                };

                var updateMethod = _saleService.UpdateSale(entity);
                if (updateMethod.Success)
                {
                    return RedirectToAction("Index");
                }
                TempData["Error"] = control.Message;
                return RedirectToAction("Index");
            }

            TempData["Error"] = control.Message;
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> GetStocks(int productId)
        {
            var result = await _stockService.GetStockQuantityByProductIdAsync(productId);
            if (result.Success)
            {
                return Content(result.Data.ToString());
            }
            return Content("");
        }
    }
}

MvcWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcWebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
</head>
<body style="font-family:Poppins">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Satış Yönetimi</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Müşteriler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Ürünler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Kategoriler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Purchase" asp-action="Index">Alışlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sale" asp-action="Index">Satışlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Index">Raporlar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcWebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>