MvcWebUI/Controllers/PurchaseController.cs
using Business.Abstract;
using Entities.DTOs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.Controllers
{
    public class PurchaseController : Controller
    {
        private readonly IPurchaseService _purchaseService;

        private readonly ICustomerService _customerService;

        private readonly IProductService _productService;

        private readonly IStockService _stockService;

        public PurchaseController(IPurchaseService purchaseService, ICustomerService customerService, IProductService productService, IStockService stockService)
        {
            _purchaseService = purchaseService;
            _customerService = customerService;
            _productService = productService;
            _stockService = stockService;
        }

        public async Task<IActionResult> Index()
        {
            var getCustomerList = _customerService.GetAllCustomers();
            List<SelectListItem> getDropdownCustomerList = (from a in getCustomerList.Data
                                                            select new SelectListItem
                                                            {
                                                                Text = string.Concat(a.Customertitle, " ", a.Customernumber),
                                                                Value = a.Id.ToString()
                                                            }
                                                 ).ToList();
            ViewBag.Customers = getDropdownCustomerList;


            var getProductList = _productService.GetAllProducts();
            List<SelectListItem> getDropdownProductList = (from a in getProductList.Data
                                                           select new SelectListItem
                                                           {
                                                               Text = string.Concat(a.Name, " ", a.Salesprice, " ", "TL"),
                                                               Value = a.Id.ToString()
                                                           }
                                                 ).ToList();
            ViewBag.Products = getDropdownProductList;

            var result = await _purchaseService.GetAllPurchasesAsync();

            return View(new AllPurchaseDto
            {
                ListPurchases = result.Data

            });
        }

        [HttpPost]
        public async Task<IActionResult> GetById(int id)
        {
            var result = await _purchaseService.GetPurchaseByIdAsync(id);
            if (result.Success)
            {
                return Json(new AllPurchaseDto
                {
                    Purchase = result.Data
                });
            }
            TempData["Error"] = result.Message;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var getData = _purchaseService.GetPurchaseByIdAsync(id).Result;
            if (getData.Success)
            {
                var deleteResult = _purchaseService.DeletePurchase(id);
                if (deleteResult.Success)
                {
                    return RedirectToAction("Index");

                }
                TempData["Error"] = deleteResult.Message;
                return RedirectToAction("Index");
            }
            TempData["Error"] = getData.Message;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Add(AllPurchaseDto model)
        {
            var entity = new CreatePurchaseDto
            {
                ProductId = model.CreatePurchase.ProductId,
                Quantity = model.CreatePurchase.Quantity,
                Price = model.CreatePurchase.Price,
                CustomerId = model.CreatePurchase.CustomerId,
            };

            var result = _purchaseService.AddPurchase(entity);
            if (result.Success)
            {
                return RedirectToAction("Index");
            }
            TempData["Error"] = result.Message;
            return RedirectToAction("Index");

        }

        public IActionResult Edit(AllPurchaseDto model)
        {
            var control = _purchaseService.GetPurchaseByIdAsync(model.UpdatePurchase.Id).Result;
            if (control.Success)
            {
                var entity = new UpdatePurchaseDto
                {
                    Id = model.UpdatePurchase.Id,
                    ProductId = model.UpdatePurchase.ProductId,
                    Quantity = model.UpdatePurchase.Quantity,
                    Price = model.UpdatePurchase.Price,
                    CustomerId = model.UpdatePurchase.CustomerId,
                };

                var updateMethod = _purchaseService.UpdatePurchase(entity);
                if (updateMethod.Success)
                {
                    return RedirectToAction("Index");
                }
                TempData["Error"] = control.Message;
                return RedirectToAction("Index");
            }

            TempData["Error"] = control.Message;
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> GetStocks(int productId)
        {
            var result = await _stockService.GetStockQuantityByProductIdAsync(productId);
            if (result.Success)
            {
                return Content(result.Data.ToString());
            }
            return Content("");
        }

    }
}

MvcWebUI/Views/Purchase/Index.cshtml
@model Entities.DTOs.AllPurchaseDto

<div style="margin-bottom:20px;text-align: right;">
    <div class="row">
        <div class="col-md-9">
        </div>
        <div class="col-md-3">
            <button class="btn btn-primary" id="showAddForm">Alış Ekle</button>
        </div>
    </div>
</div>

@if (TempData["Error"]! != null)
{
    <div style="margin-bottom:20px" class="alert alert-danger" role="alert">

        <div class="text-danger">@TempData["Error"]</div>
    </div>

}

<div id="addFormContainer" class="card" style="margin-bottom:20px;padding:15px;box-shadow: 5px 4px 12px 0px #00000052;display:none">
    <div class="row">
        <div class="col-md-12">
            <form asp-controller="Purchase" asp-action="Add" method="post">
                <div class="form-group row">
                    <label class="col-md-2 col-form-label"><strong>Müşteri Adı</strong></label>
                    <div class="col-md-10">
                        @Html.DropDownListFor(x=>x.CreatePurchase.CustomerId,(List<SelectListItem>)ViewBag.Customers,new {@class="form-control form-control-sm"})
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-2 col-form-label"><strong>Ürün Adı</strong></label>
                    <div class="col-md-10">
                        @Html.DropDownListFor(x=>x.CreatePurchase.ProductId,(List<SelectListItem>)ViewBag.Products,new {@class="form-control form-control-sm",onchange = "updateStock()",id="productId" })
                    </div>
                    <label class="col-md-2 col-form-label"></label>
                    <div class="col-md-10" id="stockMessage">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-2 col-form-label"><strong>Alış Fiyatı</strong></label>
                    <div class="col-md-10">
                        <input type="number" asp-for="CreatePurchase.Price" class="form-control form-control-sm" placeholder="Alış fiyatı giriniz" />
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-2 col-form-label"><strong>Alış Adeti</strong></label>
                    <div class="col-md-10">
                        <input type="number" asp-for="CreatePurchase.Quantity" class="form-control form-control-sm" placeholder="Alış adeti giriniz" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-10 offset-md-2">
                        <a id="hideAddForm" class="btn btn-danger btn-sm" style="color:white">Vazgeç</a>
                        <button type="submit" class="btn btn-primary btn-sm">Kaydet</button>
                    </div>
                </div>
            </form>

        </div>

    </div>
</div>

<div id="editFormContainer" class="card" style="margin-bottom:20px;padding:15px;box-shadow: 5px 4px 12px 0px #00000052;display:none">
    <div class="row">
        <div class="col-md-12">
            <form asp-controller="Purchase" asp-action="Edit" method="post">
                <input type="hidden" id="id" asp-for="UpdatePurchase.Id" />
                <div class="form-group row">
                    <label class="col-md-2 col-form-label"><strong>Müşteri Adı</strong></label>
                    <div class="col-md-10">
                        @Html.DropDownListFor(x=>x.UpdatePurchase.CustomerId,(List<SelectListItem>)ViewBag.Customers,new {@class="form-control form-control-sm"})
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-2 col-form-label"><strong>Ürün Adı</strong></label>
                    <div class="col-md-10">
                        @Html.DropDownListFor(x=>x.UpdatePurchase.ProductId,(List<SelectListItem>)ViewBag.Products,new {@class="form-control form-control-sm",onchange = "updateStockForUpdate()",id="productIdUpdate"})
                    </div>
                    <label class="col-md-2 col-form-label"></label>
                    <div class="col-md-10" id="updateStockForUpdate">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-2 col-form-label"><strong>Alış Fiyatı</strong></label>
                    <div class="col-md-10">
                        <input type="number" id="price" asp-for="UpdatePurchase.Price" class="form-control form-control-sm" placeholder="Alış fiyatı giriniz" />
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-2 col-form-label"><strong>Alış Adeti</strong></label>
                    <div class="col-md-10">
                        <input type="number" id="quantity" asp-for="UpdatePurchase.Quantity" class="form-control form-control-sm" placeholder="Alış adeti giriniz" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-10 offset-md-2">
                        <a id="hideEditForm" class="btn btn-danger btn-sm" style="color:white">Vazgeç</a>
                        <button type="submit" class="btn btn-primary btn-sm">Kaydet</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div id="purchaseListContainer" class="card" style="padding:15px;box-shadow: 5px 4px 12px 0px #00000052">
    <table id="dataTable">
        <thead>
            <tr>
                <th>ID</th>
                <th>Müşteri</th>
                <th>Ürün</th>
                <th>Alış Adeti</th>
                <th>Alış Fiyatı</th>
                <th>Toplam Fiyat</th>
                <th>Olş. Tarihi</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ListPurchases)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.CustomerName</td>
                    <td>@item.ProductName</td>
                    <td>@item.Quantity Adet</td>
                    <td>@item.Price TL</td>
                    <td>@item.Amount TL</td>
                    <td>@item.Date</td>
                    <td align="right">
                        <button onclick="editItem(@item.Id)" class="btn btn-success mr-2 btn-sm">Düzenle</button>
                    </td>
                    <td align="right">
                        <form action="/purchase/delete" method="post" style="display: inline">
                            <input type="hidden" name="Id" value="@item.Id" />
                            <button type="submit" class="btn btn-outline-danger btn-sm">Sil</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>


<script>
    $(document).ready(function () {
        $('#dataTable').DataTable({
            language: {
                url: "https://cdn.datatables.net/plug-ins/1.10.20/i18n/Turkish.json"
            }
        });
    });
    document.getElementById("showAddForm").addEventListener("click", function () {
        document.getElementById("addFormContainer").style.display = "block";
        $('#editFormContainer').hide();

    });

    document.getElementById("hideAddForm").addEventListener("click", function () {
        document.getElementById("addFormContainer").style.display = "none";
        $('#editFormContainer').hide();

    });

    document.getElementById("hideEditForm").addEventListener("click", function () {
        document.getElementById("editFormContainer").style.display = "none";
    });

    function editItem(itemId) {
        $.ajax({
            url: '/Purchase/GetById',
            type: 'POST',
            data: { id: itemId },
            success: function (result) {
                $('#id').val(result.purchase.id);
                $('#quantity').val(result.purchase.quantity);
                $('#productIdUpdate').val(result.purchase.productId);
                $('#price').val(result.purchase.price);

                $('#editFormContainer').show();
                $('#addFormContainer').hide();

            },
            error: function (error) {

            }
        });
    }

    $(function () {
        $('#editForm').submit(function (e) {
            e.preventDefault();

            $.ajax({
                url: '/Purchase/Edit',
                type: 'POST',
                data: $('#editForm').serialize(),
                success: function (result) {
                    location.reload();
                    $('#editFormContainer').hide();
                    $('#addFormContainer').hide();


                },
                error: function (error) {

                }
            });
        });
    });


    async function updateStock() {
        debugger
        var selectedProductId = document.getElementById("productId").value;
        console.log(selectedProductId)
        try {
            var response = await fetch('@Url.Action("GetStocks", "Purchase")?productId=' + selectedProductId);
            var data = await response.text();
            if (data > 0) {

                document.getElementById("stockMessage").innerHTML = "<div class='alert alert-success alert-dismissible fade show' role='alert'><small><strong>Bu ürüne ait stok adeti: " + data + "</strong></small><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button></div>"
            }
            else {
                document.getElementById("stockMessage").innerHTML = "<div class='alert alert-danger alert-dismissible fade show' role='alert'><small><strong>Bu ürüne ait stok bulunmamaktadır!</strong></small><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button></div>"
            }

        } catch (error) {
            console.log(error);
        }
    }


       async function updateStockForUpdate() {
        debugger
        var selectedProductId = document.getElementById("productIdUpdate").value;
       var test=document.getElementById("stockMessageForUpdate").innerHTML
        console.log(test)
        try {
            var response = await fetch('@Url.Action("GetStocks", "Purchase")?productId=' + selectedProductId);
            var data = await response.text();
            if (data > 0) {

                document.getElementById("stockMessageForUpdate").innerHTML = "<div class='alert alert-success alert-dismissible fade show' role='alert'><small><strong>Bu ürüne ait stok adeti: " + data + "</strong></small><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button></div>"
            }
            else {
                document.getElementById("stockMessageForUpdate").innerHTML = "<div class='alert alert-danger alert-dismissible fade show' role='alert'><small><strong>Bu ürüne ait stok bulunmamaktadır!</strong></small><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button></div>"
            }

        } catch (error) {
            console.log(error);
        }
    }

</script>